import { ArrowDown, ArrowUp, ChevronsUpDown, Edit3, Trash2 } from 'lucide-react'
import type { Player } from '../types'

interface PlayerTableProps { players: Player[]; sortKey: keyof Player; sortDirection: 'asc' | 'desc'; onSort: (key: keyof Player) => void; onEdit: (player: Player) => void; onDelete: (player: Player) => void }
const columns: { key: keyof Player; label: string }[] = [{ key: 'playerName', label: 'Player' }, { key: 'email', label: 'Contact' }, { key: 'registeredAt', label: 'Registered' }, { key: 'status', label: 'Status' }]
function SortButton({ column, sortKey, sortDirection, onSort }: { column: keyof Player; sortKey: keyof Player; sortDirection: 'asc' | 'desc'; onSort: (key: keyof Player) => void }) { const Icon = sortKey !== column ? ChevronsUpDown : sortDirection === 'asc' ? ArrowUp : ArrowDown; return <button className="sort-button" onClick={() => onSort(column)} aria-label={`Sort by ${column}`}><Icon size={14} /></button> }
export function PlayerTable({ players, sortKey, sortDirection, onSort, onEdit, onDelete }: PlayerTableProps) {
  return <div className="table-scroll"><table><thead><tr>{columns.map((column) => <th key={column.key}><span>{column.label}</span><SortButton column={column.key} sortKey={sortKey} sortDirection={sortDirection} onSort={onSort} /></th>)}<th aria-label="Actions" /></tr></thead><tbody>{players.map((player) => <tr key={player.id}><td><div className="player-cell"><span className="player-avatar">{player.playerName.slice(0, 2).toUpperCase()}</span><div><strong>{player.playerName}</strong><small>ID-{player.id}</small></div></div></td><td><span className="email">{player.email}</span><small className="phone">{player.phone}</small></td><td><span>{new Date(player.registeredAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</span><small>{new Date(player.registeredAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</small></td><td><span className={`status status-${player.status}`}><i />{player.status}</span></td><td><div className="row-actions"><button className="icon-button" onClick={() => onEdit(player)} aria-label={`Edit ${player.playerName}`}><Edit3 size={16} /></button><button className="icon-button danger-hover" onClick={() => onDelete(player)} aria-label={`Delete ${player.playerName}`}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div>
}
